use_frameworks!

target 'CYWebviewController_Example' do
  pod 'CYWebviewController', :path => '../'

  target 'CYWebviewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
